language: java
jdk:
- oraclejdk8
script:
- mvn clean install
deploy:
  file: bintray.json
  provider: bintray
  user: genstarobot
  skip_cleanup: true
  secure: "RKeZIzbPj2L0bt7VTd4M4GbYTs92Uw/xrxz+fEl0vJ6NlrFN+SmU5BHAGqDzv2gpcqkgg1Hahk4N4aqoqP5EDdfstnx1EJZmEUp4FNI2kWMS5SBWaPTb9DG/nQQI2effP2LAeuhazxXIykK0U8gVrU3H+nZl9ZhlqbcEJ2QYYoM1K/HANycqlRMBGIwx76Rcm5vbyLKvfpie6yF+YSqhA0vI8T6oRMVmYVQCkqVW/7yUy0RtYq5bdtYJZQ9CXxFLaM1PVa4mG2bt3aKFuBMBii55gOAwVj4AlG0pXe0vGF40FOK9fNhx720gSa4e339Jl/zzoAgf3VbNFCjdlUBLscyx20LtwPsfHZ906cIleMOWx8LFHGQWu2s1UyfvdXNrfyS535hzChnWzh57FfgQezdfkN57/3DZ8X87gtDPH4n2qPm8OdLNnvoGMeacsyqX7mNZ/I3iRGwYWQGSZwb0IKF9b1uIjWZeGqymz7qUU/ZFchJvvCOtpc2IeblScVgypLgxbOgYwGfyOjslOzP9hfV0smDJE5PQGSPhuomcnMkoNGfNlTWYivh3AerGD1duUinngqKBdChy4UQNaiQPyKdxQgJ6DPp0s1X0gDwjKlYVx3Dz3CgtzHrX9ozrwUoLwjX1hR46Zvr05uy6Zwl0bdmSkdyHhFv/ubn/XnMLHhU="

